### ISSUE TITLE
Maintenance of inka

### ISSUE THREAD

**Issue by sysid** [salkirr/wg-compose#1]
@salkirr , I appreciate your work on inka very much, so I decided to create a fork to continue developing it. 
Maybe you want to post a note on your inka repo to point to new successor for the interested.

Sorry for abusing this repo's issues but I did not find another way to get in touch with you.

**Comment by salkirr** [comment]
Hi. No problem. Seems like I removed email from my profile some time ago.

I added mention of your fork in the readme.
